# Generated by Django 6.1 on 2026-09-01 19:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InquiryLead',
        ),
        migrations.AlterModelOptions(
            name='admissionbatch',
            options={'ordering': ['sort_order', 'enroll_start_date'], 'verbose_name': '招生期別', 'verbose_name_plural': '招生期別管理'},
        ),
        migrations.AlterModelOptions(
            name='curriculummodule',
            options={'ordering': ['sort_order', 'module_number'], 'verbose_name': '課程模組', 'verbose_name_plural': '7大課程模組管理'},
        ),
        migrations.AlterModelOptions(
            name='facility',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': '教學設備設施', 'verbose_name_plural': '教學設備設施管理'},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': '常見問答 (FAQ)', 'verbose_name_plural': '常見問答 (FAQ) 管理'},
        ),
        migrations.AlterModelOptions(
            name='sitesetting',
            options={'verbose_name': '全域站台與宣傳設定', 'verbose_name_plural': '全域站台與宣傳設定'},
        ),
        migrations.AlterModelOptions(
            name='studentproject',
            options={'ordering': ['-is_featured', 'sort_order', '-created_at'], 'verbose_name': '學員專題作品', 'verbose_name_plural': '14組學員作品集管理'},
        ),
        migrations.AlterModelOptions(
            name='techcard',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': '核心技術卡片', 'verbose_name_plural': '核心技術卡片管理'},
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='turnstile_secret_key',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='turnstile_site_key',
        ),
        migrations.AddField(
            model_name='curriculummodule',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='建立時間'),
        ),
        migrations.AddField(
            model_name='curriculummodule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新時間'),
        ),
        migrations.AddField(
            model_name='studentproject',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新時間'),
        ),
        migrations.AlterField(
            model_name='admissionbatch',
            name='apply_url',
            field=models.URLField(max_length=500, verbose_name='台灣就業通線上報名網址'),
        ),
        migrations.AlterField(
            model_name='admissionbatch',
            name='batch_name',
            field=models.CharField(max_length=100, verbose_name='期別名稱 (例：第 1 期)'),
        ),
        migrations.AlterField(
            model_name='admissionbatch',
            name='click_count',
            field=models.IntegerField(default=0, verbose_name='報名按鈕累計點擊數'),
        ),
        migrations.AlterField(
            model_name='admissionbatch',
            name='course_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='台灣就業通課程代碼'),
        ),
        migrations.AlterField(
            model_name='admissionbatch',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='建立時間'),
        ),
        migrations.AlterField(
            model_name='admissionbatch',
            name='sort_order',
            field=models.IntegerField(default=0, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='admissionbatch',
            name='status_override',
            field=models.CharField(choices=[('auto', '系統自動判定'), ('open', '熱烈報名中'), ('closing_soon', '即將截止'), ('full', '已額滿'), ('training', '培訓進行中'), ('upcoming', '即將開放報名'), ('ended', '本期已截止'), ('hidden', '前台隱藏')], default='auto', max_length=20, verbose_name='狀態覆寫標籤'),
        ),
        migrations.AlterField(
            model_name='admissionbatch',
            name='training_end_date',
            field=models.DateField(verbose_name='結訓日期'),
        ),
        migrations.AlterField(
            model_name='admissionbatch',
            name='training_start_date',
            field=models.DateField(verbose_name='開訓日期'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='建立時間'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='cta_link',
            field=models.CharField(default='#batches', max_length=200, verbose_name='行動按鈕連結'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='cta_target',
            field=models.CharField(choices=[('_self', '當前視窗 (_self)'), ('_blank', '新分頁 (_blank)')], default='_self', max_length=20, verbose_name='開啟方式'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='cta_text',
            field=models.CharField(default='立即探索期別', max_length=50, verbose_name='行動按鈕文字'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='carousels/', verbose_name='電腦版圖片'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='image_alt',
            field=models.CharField(max_length=200, verbose_name='無障礙圖片替代文字 (Alt)'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否啟用'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='mobile_image',
            field=models.ImageField(blank=True, null=True, upload_to='carousels/', verbose_name='行動版圖片'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='sort_order',
            field=models.IntegerField(default=0, verbose_name='排序權重 (越小越前)'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='subtitle',
            field=models.TextField(blank=True, verbose_name='副標題/宣傳文案'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='title',
            field=models.CharField(max_length=200, verbose_name='輪播主標題'),
        ),
        migrations.AlterField(
            model_name='curriculummodule',
            name='category_tab',
            field=models.CharField(max_length=50, verbose_name='分類標籤 (例：基礎與設計)'),
        ),
        migrations.AlterField(
            model_name='curriculummodule',
            name='description',
            field=models.TextField(verbose_name='課程大綱詳細說明'),
        ),
        migrations.AlterField(
            model_name='curriculummodule',
            name='hours',
            field=models.IntegerField(verbose_name='時數 (小時)'),
        ),
        migrations.AlterField(
            model_name='curriculummodule',
            name='module_name',
            field=models.CharField(max_length=100, verbose_name='模組名稱'),
        ),
        migrations.AlterField(
            model_name='curriculummodule',
            name='module_number',
            field=models.CharField(max_length=10, verbose_name='模組編號 (例：M1)'),
        ),
        migrations.AlterField(
            model_name='curriculummodule',
            name='sort_order',
            field=models.IntegerField(default=0, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='description',
            field=models.TextField(verbose_name='設施亮點說明'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='facility_name',
            field=models.CharField(max_length=100, verbose_name='設施名稱'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='facilities/', verbose_name='教室實景照片'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='image_alt',
            field=models.CharField(max_length=200, verbose_name='照片替代文字'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='sort_order',
            field=models.IntegerField(default=0, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(verbose_name='解答說明'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='category',
            field=models.CharField(max_length=50, verbose_name='問答類別 (例：生活津貼)'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(max_length=255, verbose_name='問題題目'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='sort_order',
            field=models.IntegerField(default=0, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='announcement_bar_enabled',
            field=models.BooleanField(default=True, verbose_name='啟用頂部快訊跑馬條'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='announcement_link',
            field=models.CharField(default='#batches', max_length=200, verbose_name='快訊點擊連結'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='announcement_text',
            field=models.CharField(default='115 年度第 1 期「前端網頁技術與AI應用」熱烈招生中！待業民眾享全額免費受訓與職訓生活津貼補助！', max_length=255, verbose_name='快訊文字'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='contact_address',
            field=models.CharField(default='新北市泰山區貴子里致遠新村 55 之 1 號', max_length=200, verbose_name='職訓場地址'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='contact_phone',
            field=models.CharField(default='(02) 2901-8274', max_length=50, verbose_name='諮詢電話'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='discord_channel_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='Discord Channel ID'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='discord_invite_url',
            field=models.CharField(default='https://discord.gg/TrerFKG', max_length=200, verbose_name='Discord 邀請連結'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='discord_server_id',
            field=models.CharField(default='463880731828158464', max_length=50, verbose_name='Discord Server ID'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='網站 Favicon'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='footer_copyright',
            field=models.CharField(default='勞動部勞動力發展署北基宜花金馬分署 泰山職業訓練場 版權所有', max_length=200, verbose_name='頁尾版權宣告'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='ga4_measurement_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='GA4 Measurement ID (例：G-XXXXXXXXXX)'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='gtm_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='GTM Container ID (例：GTM-XXXXXXX)'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='og_image',
            field=models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='社群分享圖 (OG Image)'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='seo_description',
            field=models.TextField(default='從零開始的網頁設計課程，政府自辦待業者完全免費，920小時培訓前端開發工程師職能。', verbose_name='SEO 描述 (Description)'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='site_logo',
            field=models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='全站 Logo'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='site_title',
            field=models.CharField(default='泰山職訓「前端網頁技術與AI應用」招生推廣網站', max_length=200, verbose_name='網站標題'),
        ),
        migrations.AlterField(
            model_name='studentproject',
            name='batch_tag',
            field=models.CharField(default='前端專班結訓成果', max_length=50, verbose_name='期別標籤'),
        ),
        migrations.AlterField(
            model_name='studentproject',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='建立時間'),
        ),
        migrations.AlterField(
            model_name='studentproject',
            name='demo_url',
            field=models.URLField(max_length=500, verbose_name='線上 Demo 網址'),
        ),
        migrations.AlterField(
            model_name='studentproject',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否啟用'),
        ),
        migrations.AlterField(
            model_name='studentproject',
            name='project_name',
            field=models.CharField(max_length=150, verbose_name='專題作品名稱'),
        ),
        migrations.AlterField(
            model_name='studentproject',
            name='sort_order',
            field=models.IntegerField(default=0, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='studentproject',
            name='student_name',
            field=models.CharField(max_length=100, verbose_name='學員姓名'),
        ),
        migrations.AlterField(
            model_name='studentproject',
            name='tech_tags',
            field=models.CharField(max_length=200, verbose_name='技術標籤 (以逗點分隔)'),
        ),
        migrations.AlterField(
            model_name='studentproject',
            name='view_count',
            field=models.IntegerField(default=0, verbose_name='瀏覽次數'),
        ),
        migrations.AlterField(
            model_name='techcard',
            name='category_tab',
            field=models.CharField(max_length=50, verbose_name='分類標籤'),
        ),
        migrations.AlterField(
            model_name='techcard',
            name='description',
            field=models.CharField(max_length=255, verbose_name='技術重點摘要'),
        ),
        migrations.AlterField(
            model_name='techcard',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='tech_icons/', verbose_name='Icon圖標'),
        ),
        migrations.AlterField(
            model_name='techcard',
            name='image_alt',
            field=models.CharField(max_length=200, verbose_name='圖標替代文字'),
        ),
        migrations.AlterField(
            model_name='techcard',
            name='sort_order',
            field=models.IntegerField(default=0, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='techcard',
            name='tech_name',
            field=models.CharField(max_length=100, verbose_name='技術名稱 (例：Vue.js 3)'),
        ),
    ]
