# Generated by Django 6.1 on 2026-09-03 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_delete_inquirylead_alter_admissionbatch_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admissionbatch',
            options={'ordering': ['sort_order', 'enroll_start_date'], 'verbose_name': '招生期別', 'verbose_name_plural': '招生期別與官方連結管理'},
        ),
        migrations.AlterModelOptions(
            name='studentproject',
            options={'ordering': ['-is_featured', 'sort_order', '-created_at'], 'verbose_name': '學員專題作品', 'verbose_name_plural': '學員作品集管理'},
        ),
        migrations.AddField(
            model_name='admissionbatch',
            name='applicants_count',
            field=models.IntegerField(default=0, verbose_name='目前報名人數'),
        ),
        migrations.AddField(
            model_name='admissionbatch',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最後外部同步時間'),
        ),
        migrations.AddField(
            model_name='admissionbatch',
            name='planned_trainees',
            field=models.IntegerField(default=24, verbose_name='預定招訓人數'),
        ),
        migrations.AddField(
            model_name='admissionbatch',
            name='screening_date',
            field=models.DateField(blank=True, null=True, verbose_name='甄試日期'),
        ),
        migrations.AlterField(
            model_name='admissionbatch',
            name='apply_url',
            field=models.URLField(max_length=500, verbose_name='台灣就業通官方報名網址'),
        ),
        migrations.AlterField(
            model_name='admissionbatch',
            name='click_count',
            field=models.IntegerField(default=0, verbose_name='報名點擊次數 (轉換追蹤)'),
        ),
        migrations.AlterField(
            model_name='admissionbatch',
            name='course_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='台灣就業通課程代碼 (例：159268)'),
        ),
        migrations.AlterField(
            model_name='admissionbatch',
            name='status_override',
            field=models.CharField(choices=[('auto', '系統自動判定'), ('open', '熱烈報名中'), ('closing_soon', '即將截止'), ('full', '已額滿'), ('screening', '甄試作業中'), ('preparing', '開訓準備中'), ('training', '培訓進行中'), ('upcoming', '即將開放報名'), ('ended', '本期已截止'), ('hidden', '前台隱藏')], default='auto', max_length=20, verbose_name='狀態顯示模式'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='announcement_text',
            field=models.CharField(default='🔥 115 年度第 1 期熱烈招生中！待業民眾享全額免費受訓與生活津貼補助！', max_length=255, verbose_name='快訊文字'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='footer_copyright',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='頁尾版權宣告 (選填)'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='site_title',
            field=models.CharField(default='泰山職訓－前端網頁技術與AI應用', max_length=200, verbose_name='網站標題'),
        ),
    ]
