# Generated by Django 6.1 on 2026-09-03 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_alter_admissionbatch_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentproject',
            name='tech_tags',
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='footer_copyright',
            field=models.CharField(blank=True, default='本網站為前端班師資自主推廣與學員成果展示網頁', max_length=200, verbose_name='頁尾宣告 (選填)'),
        ),
    ]
