# Generated by Django 6.1 on 2026-09-04 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_remove_studentproject_tech_tags_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admissionbatch',
            options={'ordering': ['sort_order', 'enroll_start_date'], 'verbose_name': '招生期別 (爬蟲儲存)', 'verbose_name_plural': '招生期別 (🤖 台灣就業通爬蟲自動同步)'},
        ),
        migrations.AlterField(
            model_name='admissionbatch',
            name='applicants_count',
            field=models.IntegerField(default=0, help_text='🤖 爬蟲自動同步：來自台灣就業通的最新報名人數', verbose_name='目前報名人數'),
        ),
        migrations.AlterField(
            model_name='admissionbatch',
            name='apply_url',
            field=models.URLField(help_text='🤖 爬蟲自動對應之官方就業通報名連結（亦可手動覆寫）', max_length=500, verbose_name='台灣就業通官方報名網址'),
        ),
        migrations.AlterField(
            model_name='admissionbatch',
            name='batch_name',
            field=models.CharField(help_text='🤖 爬蟲自動同步：班級名稱', max_length=100, verbose_name='期別名稱 (例：第 1 期)'),
        ),
        migrations.AlterField(
            model_name='admissionbatch',
            name='click_count',
            field=models.IntegerField(default=0, help_text='📊 官網前台民眾點擊「前往報名」按鈕的累計次數（數據轉換成效）', verbose_name='報名點擊次數 (轉換追蹤)'),
        ),
        migrations.AlterField(
            model_name='admissionbatch',
            name='course_code',
            field=models.CharField(blank=True, help_text='🤖 爬蟲追蹤識別碼：以此代碼向台灣就業通爬取該班最新狀態', max_length=50, verbose_name='台灣就業通課程代碼 (例：159268)'),
        ),
        migrations.AlterField(
            model_name='admissionbatch',
            name='enroll_end_date',
            field=models.DateField(help_text='🤖 爬蟲自動同步：官方報名截止日期', verbose_name='報名截止日期'),
        ),
        migrations.AlterField(
            model_name='admissionbatch',
            name='enroll_start_date',
            field=models.DateField(help_text='🤖 爬蟲自動同步：官方報名開始日期', verbose_name='報名起始日期'),
        ),
        migrations.AlterField(
            model_name='admissionbatch',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='🤖 爬蟲最後一次成功連線台灣就業通並更新資料庫的時間', null=True, verbose_name='最後外部同步時間'),
        ),
        migrations.AlterField(
            model_name='admissionbatch',
            name='planned_trainees',
            field=models.IntegerField(default=24, help_text='🤖 爬蟲自動同步：官方預定招訓人數', verbose_name='預定招訓人數'),
        ),
        migrations.AlterField(
            model_name='admissionbatch',
            name='screening_date',
            field=models.DateField(blank=True, help_text='🤖 爬蟲自動同步：官方甄試日期', null=True, verbose_name='甄試日期'),
        ),
        migrations.AlterField(
            model_name='admissionbatch',
            name='sort_order',
            field=models.IntegerField(default=0, help_text='數字越小越靠前，預設 0', verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='admissionbatch',
            name='status_override',
            field=models.CharField(choices=[('auto', '系統自動判定'), ('open', '熱烈報名中'), ('closing_soon', '即將截止'), ('full', '已額滿'), ('screening', '甄試作業中'), ('preparing', '開訓準備中'), ('training', '培訓進行中'), ('upcoming', '即將開放報名'), ('ended', '本期已截止'), ('hidden', '前台隱藏')], default='auto', help_text='💡 建議維持「系統自動判定」（由系統依爬蟲日期動態計算）。若需緊急手動干預或強制隱藏才做變更', max_length=20, verbose_name='狀態顯示模式'),
        ),
        migrations.AlterField(
            model_name='admissionbatch',
            name='total_hours',
            field=models.IntegerField(default=920, help_text='官方核定總訓練時數（預設 920 小時）', verbose_name='總訓練時數'),
        ),
        migrations.AlterField(
            model_name='admissionbatch',
            name='training_end_date',
            field=models.DateField(help_text='🤖 爬蟲自動同步：官方預計結訓日期', verbose_name='結訓日期'),
        ),
        migrations.AlterField(
            model_name='admissionbatch',
            name='training_start_date',
            field=models.DateField(help_text='🤖 爬蟲自動同步：官方正式開訓日期', verbose_name='開訓日期'),
        ),
    ]
