# Generated by Django 6.1 on 2026-09-05 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_alter_admissionbatch_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='設施副標題'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='facility_name',
            field=models.CharField(max_length=100, verbose_name='設施主標題'),
        ),
    ]
