# Generated by Django 6.1 on 2026-09-05 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_facility_subtitle_alter_facility_facility_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionbatch',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='軟刪除時間'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='軟刪除時間'),
        ),
        migrations.AlterField(
            model_name='curriculummodule',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='軟刪除時間'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='軟刪除時間'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='軟刪除時間'),
        ),
        migrations.AlterField(
            model_name='studentproject',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='軟刪除時間'),
        ),
        migrations.AlterField(
            model_name='techcard',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='軟刪除時間'),
        ),
    ]
