# Generated by Django 6.1 on 2026-09-24 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_alter_admissionbatch_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentproject',
            options={'ordering': ['-is_featured', 'sort_order', '-created_at', '-id'], 'verbose_name': '學員專題作品', 'verbose_name_plural': '學員作品集管理'},
        ),
        migrations.AlterField(
            model_name='studentproject',
            name='sort_order',
            field=models.IntegerField(default=1, verbose_name='排序 (預設 1 自動置頂第一名，系統會自動將其他作品順序往後順延)'),
        ),
    ]
